version: '3.14'
services:
  django:
    container_name: django
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - ./entrypoint.sh
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres
    tty: true
  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    tty: true
    logging:
      driver: none
volumes:
  postgres:
